Update odometry fusion documentation
PX4/PX4-Devguide pull request #1051
Opened 2020-06-24 21:32 UTC by marcelino-pensa

See issue https://github.com/PX4/Firmware/issues/15168

2020-06-24 22:38 UTC, hamishwillee commented
Looks great to me @TSC21 , but you're the ROS expert.

2020-06-29 23:47 UTC, hamishwillee commented
@TSC21 Please review.

2020-07-05 23:46 UTC, TSC21 requested changes
Just a small fix required and all good.

2020-07-05 23:46 UTC, TSC21 commented on en/ros/external_position_estimation.md
> +/mavros/odometry/out (`frame_id = odom`, `child_frame_id = base_link`) | [ODOMETRY](https://mavlink.io/en/messages/common.html#ODOMETRY) (`frame_id =` [MAV_FRAME_MOCAP_NED](https://mavlink.io/en/mess
```suggestion
/mavros/odometry/out (`frame_id = odom`, `child_frame_id = base_link`) | [ODOMETRY](https://mavlink.io/en/messages/common.html#ODOMETRY) (`frame_id =` [MAV_FRAME_LOCAL_FRD](https://mavlink.io/en/messages/common.html#MAV_FRAME_LOCAL_FRD)) | `vehicle_mocap_odometry`
```

2020-07-08 01:42 UTC, hamishwillee commented
@marcelino-pensa FYI I have merged this with @TSC21 correction (hope that OK with you). Thanks very much for taking the time to contribute!

2020-07-08 01:42 UTC, merged

2020-07-09 16:17 UTC, marcelino-pensa commented
Thanks @hamishwillee! I was trying to hold this back until I had my questions answered in https://github.com/PX4/Firmware/issues/15168... I can update the documentation in the future if I get an answer for that question

2020-07-15 01:23 UTC, hamishwillee commented
Cool. I tend to merge what is known as early as I can - everyone is busy, and you can hold up a lot of good info waiting on answers.