Adding Fast RTPS documentation
PX4/PX4-Devguide pull request #174
Opened 2017-06-05 07:11 UTC by VicenteEprosima

2017-06-05 08:28 UTC, LorenzMeier requested changes
Thanks, this is very helpful! To match the quality of the rest of the documentation we need a little more specific instructions in some areas.

2017-06-05 08:28 UTC, LorenzMeier commented on en/setup/fast-rtps-installation.md
> +Gtest is needed to compile the tests when building from sources.
This is not clear enough. We require in our documentation installation instructions for the major platforms (e.g. apt-get install XYZ or brew install XYZ).

2017-06-05 08:28 UTC, LorenzMeier commented on en/setup/fast-rtps-installation.md
> +Java is required to make use of our buil-in code generation tool *fastrtpsgen*.
Not detailed enough. What version of Java? Is that version already installed with the rest of PX4? (we do have Java as dependency for jMAVSim)

2017-06-05 13:37 UTC, VicenteEprosima commented on en/setup/fast-rtps-installation.md
> +Java is required to make use of our buil-in code generation tool *fastrtpsgen*.
We need 1.6 at least but jMAVSim needs 1.8.

2017-06-05 13:44 UTC, mhkabir commented on en/setup/fast-rtps-installation.md
> +Java is required to make use of our buil-in code generation tool *fastrtpsgen*.
It would make sense just to recommend 1.8. Too many options just confuse people.

2017-06-05 13:52 UTC, VicenteEprosima commented on en/setup/fast-rtps-installation.md
> +Java is required to make use of our buil-in code generation tool *fastrtpsgen*.
it seems good.

2017-06-05 13:55 UTC, VicenteEprosima commented on en/setup/fast-rtps-installation.md
> +Gtest is needed to compile the tests when building from sources.
We think is not necessary since is for test purposes. We'll avoid that in this abstract.

2017-06-15 21:14 UTC, LorenzMeier approved these changes

2017-06-15 21:14 UTC, merged