Fix astyle path
PX4/PX4-Devguide pull request #331
Opened 2017-10-27 13:01 UTC by ndepal

Also: With the recommended version of astyle 2.06 from sourceforge, I get a huge diff with `./Tools/astyle/check_code_style_all.sh`. Its so long it overflows the buffer of my terminal and I can only see the diff of `src/lib/micro-CDR/test/AllTest.cpp`, there might be more.

2017-11-05 15:35 UTC, korigod commented
The Korean version have same astyle script path issue.

2017-11-05 16:50 UTC, korigod requested changes
Commit message should describe commit itself, not some unrelated problem.

2017-11-05 22:09 UTC, hamishwillee commented
@ndepal  - what @korigod  is suggesting is that it would be good to also update https://github.com/PX4/Devguide/blob/master/kr/contribute/README.md

@FantasyJXF The whole chinese page probably needs to be re-translated: https://github.com/PX4/Devguide/blob/master/zh/contribute/README.md

2017-11-09 15:39 UTC, ndepal commented
@korigod addressed both comments

2017-11-09 22:38 UTC, merged

2017-11-09 22:41 UTC, hamishwillee commented
@ndepal Thanks for this, merged.

Regarding:

> Also: With the recommended version of astyle 2.06 from sourceforge, I get a huge diff with ./Tools/astyle/check_code_style_all.sh. Its so long it overflows the buffer of my terminal and I can only see the diff of src/lib/micro-CDR/test/AllTest.cpp, there might be more.

Have you tried the other versions of asytle, and do they give the same problems? If not, @bkueng  any reason we can might perhaps recommend a later version?

2017-11-10 07:47 UTC, bkueng commented
Well, I have 2.06 and it works for me. I don't have an explanation why the same version should give different results.
We have always had some troubles with different versions, so personally I would prefer to switch to `clang-format`.

2017-11-10 08:24 UTC, hamishwillee commented
@bkueng Seems reasonable, but won't that potentially result in lots of spurious changes too? In any case, what would have to happen, to make that happen? Not really for me to drive this :-)

2017-11-10 08:55 UTC, bkueng commented
Yes it will definitely create a large diff, which is probably why it hasn't happened yet.

2017-11-13 03:14 UTC, hamishwillee commented
Thanks @bkueng , https://github.com/PX4/Firmware/issues/8277 created for tracking if anything happens with that.