Fix more FastRTPS install commands
PX4/PX4-Devguide pull request #711
Opened 2019-01-08 10:59 UTC by julianoes

Follow up to https://github.com/PX4/Devguide/pull/705.

2019-01-08 11:01 UTC, TSC21 requested changes
We have to install and use FastCDR 1.0.8 and FastRTPS 1.6.0.

2019-01-08 11:13 UTC, julianoes commented
@TSC21 huh? I didn't change anything in that respect.

2019-01-08 11:19 UTC, TSC21 commented
Oh sorry I didn't see the all change. Do you mind changing the versions though?

2019-01-08 12:43 UTC, TSC21 approved these changes

2019-01-08 13:15 UTC, julianoes commented
No, I would have to test it to change the versions, and I don't have time to for now, sorry.

2019-01-09 05:00 UTC, hamishwillee commented on kr/setup/dev_env_linux_ubuntu.md
> +(cd eProsima_FastCDR-1.0.7-Linux && ./configure --libdir=/usr/lib && make && sudo make install)
FYI only, in future don't bother making any changes to translation branches. The round trip to translation service fixes those up for us. If you make the change then it means I have to resolve a conflict :-(.

2019-01-09 05:00 UTC, hamishwillee approved these changes

2019-01-09 05:02 UTC, merged

2019-01-09 06:21 UTC, hamishwillee commented
Thanks. Looks good. I merged on assumption that scripts are good, and I'm testing after the fact. Note that all I'm doing is testing that the scripts will set up a ubuntu environment and start gazebo. No idea how you would test FastRTPS.